"use strict";

var _interopRequireWildcard = require("@babel/runtime-corejs2/helpers/interopRequireWildcard");

var _interopRequireDefault = require("@babel/runtime-corejs2/helpers/interopRequireDefault");

exports.__esModule = true;
exports["default"] = void 0;

var _assign2 = _interopRequireDefault(require("lodash/assign"));

var _inherits = _interopRequireDefault(require("inherits"));

var _columncompiler = _interopRequireDefault(require("knex/lib/schema/columncompiler"));

var helpers = _interopRequireWildcard(require("knex/lib/helpers"));

// HDB Column Compiler
// -------
function ColumnCompiler_HDB() {
  _columncompiler["default"].apply(this, arguments);

  this.modifiers = ['unsigned', 'nullable', 'defaultTo', 'comment', 'first', 'after', 'collate'];
}

(0, _inherits["default"])(ColumnCompiler_HDB, _columncompiler["default"]); // Types
// ------

(0, _assign2["default"])(ColumnCompiler_HDB.prototype, {
  increments: 'integer not null generated by default as identity',
  bigincrements: 'bigint not null generated by default as identity',
  tinyint: 'tinyint',
  smallint: 'smallint',
  floating: 'real',
  "double": 'double',
  decimal: function decimal(precision, scale) {
    return "decimal(" + this._num(precision, 8) + ", " + this._num(scale, 2) + ")";
  },
  varchar: function varchar(length, charset) {
    return (charset === 'utf-8' ? 'nvarchar' : 'varchar') + ("(" + this._num(length, 255) + ")");
  },
  text: 'NCLOB',
  mediumtext: 'NCLOB',
  longtext: 'NCLOB',
  datetime: 'seconddate',
  timestamp: 'timestamp',
  binary: function binary(length) {
    return length ? "varbinary(" + this._num(length) + ")" : 'blob';
  },
  // Modifiers
  // ------
  comment: function comment(_comment) {
    return _comment && "comment '" + _comment + "'";
  }
});
var _default = ColumnCompiler_HDB;
exports["default"] = _default;
module.exports = exports["default"];